org.gradle.jvmargs=-Xmx2048M

loom.platform=forge

## Minecraft
minecraft_version=1.20.1

## Mod
mod_id=etched
mod_version=5.0.0-alpha.1
mod_name=Re-Etched
mod_description=An unofficial Forge 1.20.1 fork of Etched with improved and hardened internet radio playback.
archives_base_name=re-etched
maven_group=io.github.oogaboogadev

# Forge
forge_version=47.4.10
forge_loader_version=47
